/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArecaLeafPlatesRouteImport } from './routes/areca-leaf-plates'
import { Route as ArecaLeafPlatesTamilNaduRouteImport } from './routes/areca-leaf-plates-tamil-nadu'
import { Route as ArecaLeafPlatesTrichyRouteImport } from './routes/areca-leaf-plates-trichy'
import { Route as PaperPlatesRouteImport } from './routes/paper-plates'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogPalmLeafVsBambooVsBagasseRouteImport } from './routes/blog.palm-leaf-vs-bamboo-vs-bagasse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArecaLeafPlatesRoute = ArecaLeafPlatesRouteImport.update({
  id: '/areca-leaf-plates',
  path: '/areca-leaf-plates',
  getParentRoute: () => rootRouteImport,
} as any)
const ArecaLeafPlatesTamilNaduRoute =
  ArecaLeafPlatesTamilNaduRouteImport.update({
    id: '/areca-leaf-plates-tamil-nadu',
    path: '/areca-leaf-plates-tamil-nadu',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArecaLeafPlatesTrichyRoute = ArecaLeafPlatesTrichyRouteImport.update({
  id: '/areca-leaf-plates-trichy',
  path: '/areca-leaf-plates-trichy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperPlatesRoute = PaperPlatesRouteImport.update({
  id: '/paper-plates',
  path: '/paper-plates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPalmLeafVsBambooVsBagasseRoute =
  BlogPalmLeafVsBambooVsBagasseRouteImport.update({
    id: '/blog/palm-leaf-vs-bamboo-vs-bagasse',
    path: '/blog/palm-leaf-vs-bamboo-vs-bagasse',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areca-leaf-plates': typeof ArecaLeafPlatesRoute
  '/areca-leaf-plates-tamil-nadu': typeof ArecaLeafPlatesTamilNaduRoute
  '/areca-leaf-plates-trichy': typeof ArecaLeafPlatesTrichyRoute
  '/paper-plates': typeof PaperPlatesRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areca-leaf-plates': typeof ArecaLeafPlatesRoute
  '/areca-leaf-plates-tamil-nadu': typeof ArecaLeafPlatesTamilNaduRoute
  '/areca-leaf-plates-trichy': typeof ArecaLeafPlatesTrichyRoute
  '/paper-plates': typeof PaperPlatesRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areca-leaf-plates': typeof ArecaLeafPlatesRoute
  '/areca-leaf-plates-tamil-nadu': typeof ArecaLeafPlatesTamilNaduRoute
  '/areca-leaf-plates-trichy': typeof ArecaLeafPlatesTrichyRoute
  '/paper-plates': typeof PaperPlatesRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areca-leaf-plates'
    | '/areca-leaf-plates-tamil-nadu'
    | '/areca-leaf-plates-trichy'
    | '/paper-plates'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areca-leaf-plates'
    | '/areca-leaf-plates-tamil-nadu'
    | '/areca-leaf-plates-trichy'
    | '/paper-plates'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  id:
    | '__root__'
    | '/'
    | '/areca-leaf-plates'
    | '/areca-leaf-plates-tamil-nadu'
    | '/areca-leaf-plates-trichy'
    | '/paper-plates'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArecaLeafPlatesRoute: typeof ArecaLeafPlatesRoute
  ArecaLeafPlatesTamilNaduRoute: typeof ArecaLeafPlatesTamilNaduRoute
  ArecaLeafPlatesTrichyRoute: typeof ArecaLeafPlatesTrichyRoute
  PaperPlatesRoute: typeof PaperPlatesRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogPalmLeafVsBambooVsBagasseRoute: typeof BlogPalmLeafVsBambooVsBagasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areca-leaf-plates': {
      id: '/areca-leaf-plates'
      path: '/areca-leaf-plates'
      fullPath: '/areca-leaf-plates'
      preLoaderRoute: typeof ArecaLeafPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areca-leaf-plates-tamil-nadu': {
      id: '/areca-leaf-plates-tamil-nadu'
      path: '/areca-leaf-plates-tamil-nadu'
      fullPath: '/areca-leaf-plates-tamil-nadu'
      preLoaderRoute: typeof ArecaLeafPlatesTamilNaduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areca-leaf-plates-trichy': {
      id: '/areca-leaf-plates-trichy'
      path: '/areca-leaf-plates-trichy'
      fullPath: '/areca-leaf-plates-trichy'
      preLoaderRoute: typeof ArecaLeafPlatesTrichyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-plates': {
      id: '/paper-plates'
      path: '/paper-plates'
      fullPath: '/paper-plates'
      preLoaderRoute: typeof PaperPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/palm-leaf-vs-bamboo-vs-bagasse': {
      id: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      path: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      fullPath: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      preLoaderRoute: typeof BlogPalmLeafVsBambooVsBagasseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArecaLeafPlatesRoute: ArecaLeafPlatesRoute,
  ArecaLeafPlatesTamilNaduRoute: ArecaLeafPlatesTamilNaduRoute,
  ArecaLeafPlatesTrichyRoute: ArecaLeafPlatesTrichyRoute,
  PaperPlatesRoute: PaperPlatesRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogPalmLeafVsBambooVsBagasseRoute: BlogPalmLeafVsBambooVsBagasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
